# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8abb0f81814b8d6e89744b46575b730b"
name = "Adbuffs Onboard Dev"
application_url = "https://omega-crewmate-palm.ngrok-free.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://omega-crewmate-palm.ngrok-free.dev/auth/callback"
]
