# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5b5a8a8e997d68093e465221a2cd8122"
name = "Adbuffs Onboard"
application_url = "https://adbuffs-app.adbuffs.com"
embedded = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders"

# optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://adbuffs-app.adbuffs.com/auth/callback"
]

[build]
automatically_update_urls_on_dev = false
